import {
  app,
  HttpRequest,
  HttpResponseInit,
  InvocationContext,
} from "@azure/functions";

export async function htmlGenerator(
  request: HttpRequest,
  context: InvocationContext
): Promise<HttpResponseInit> {
  const name = request.query.get("name") || "Guest";
  const html = `
    <html>
      <head><title>Hello from Azure Function</title></head>
      <body style="font-family:sans-serif;text-align:center;margin-top:40px">
        <h1>👋 Hello, ${name}!</h1>
        <p>This page was dynamically generated by an <b>Azure Function (serverless Lambda)</b>.</p>
        <p>${new Date().toLocaleString()}</p>
      </body>
    </html>
  `;
  return {
    headers: { "Content-Type": "text/html" },
    body: html,
  };
}

app.http("htmlGenerator", {
  route: "htmlGenerator",
  methods: ["GET", "POST"],
  authLevel: "anonymous",
  handler: htmlGenerator,
});
